# Generated by Django 3.1.7 on 2021-03-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Artists',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='comment',
            new_name='artist',
        ),
    ]
